# Generated by Django 3.0.1 on 2020-01-06 12:59

import achivements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('award_title', models.CharField(help_text='Title Of Award', max_length=200)),
                ('award_date', models.DateField(blank=True, null=True, verbose_name='Awarded On')),
                ('award_details', models.TextField(null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to=achivements.models.file_award)),
            ],
            options={
                'ordering': ['award_date', 'award_title'],
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Conference Name', max_length=200)),
                ('title', models.CharField(help_text='Enter Title', max_length=200)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date of Conference')),
                ('certificate', models.FileField(blank=True, null=True, upload_to=achivements.models.file_conference)),
                ('conference_type', models.CharField(choices=[('N', 'National'), ('IN', 'International'), ('IEEE-N', 'IEEE-National'), ('IEEE-IN', 'IEEE-International')], default='N', max_length=20)),
            ],
            options={
                'ordering': ['date', 'name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('journal_title', models.CharField(max_length=200, verbose_name='Title of Journal')),
                ('paper_title', models.CharField(max_length=200, verbose_name='Title of Paper')),
                ('date', models.DateField(blank=True, verbose_name='Journal Presentation Date')),
                ('journal_type', models.CharField(choices=[('N', 'National'), ('IN', 'International'), ('IEEE-N', 'IEEE-National'), ('IEEE-IN', 'IEEE-International')], default='N', max_length=20)),
                ('impact_factor', models.FloatField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to=achivements.models.file_journal)),
            ],
            options={
                'ordering': ['date', 'journal_title', 'paper_title'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200, verbose_name='Workshop Title')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Held on')),
                ('workshop_type', models.CharField(choices=[('N', 'National'), ('IN', 'International'), ('IEEE-N', 'IEEE-National'), ('IEEE-IN', 'IEEE-International')], default='N', max_length=20)),
                ('location', models.CharField(max_length=200, verbose_name='Held at(location)')),
                ('certificate', models.FileField(blank=True, null=True, upload_to=achivements.models.file_workshop)),
            ],
            options={
                'ordering': ['date', 'topic'],
            },
        ),
    ]
